// Generated by CoffeeScript 1.10.0
(function() {
  var conversionamento, form, inbin, indec, processForm, vedisebin;

  vedisebin = function(numerodacontrollare) {
    console.log("Avviato numerodacontrollare");
    while (numerodacontrollare > 0) {
      if (numerodacontrollare % 10 !== 0 && numerodacontrollare % 10 !== 1) {
        return false;
      }
      numerodacontrollare = parseInt(numerodacontrollare / 10);
    }
    return true;
  };

  inbin = function(numerodec) {
    var contatore, numerocorrente, resti;
    console.log("Avviato inbin");
    numerocorrente = numerodec;
    resti = 0;
    contatore = 1;
    while (numerocorrente > 0) {
      resti = resti + numerocorrente % 2 * contatore;
      numerocorrente = parseInt(numerocorrente / 2);
      contatore = contatore * 10;
    }
    return resti;
  };

  indec = function(numerobin) {
    var i, numerocorrente, numerodauscire;
    console.log("avviato indec");
    numerocorrente = numerobin;
    numerodauscire = 0;
    i = 0;
    if (vedisebin(numerobin)) {
      console.log("Uscito da numerodacontrollare");
      while (numerocorrente > 0) {
        console.log("ciclo indec");
        numerodauscire = numerodauscire + numerocorrente % 10 * Math.pow(2, i);
        i++;
        numerocorrente = parseInt(numerocorrente / 10);
      }
      console.log("fine ciclo indec");
      return numerodauscire;
    } else {
      return "Non va bene";
    }
  };

  conversionamento = function(numerodaconvertire, bindec) {
    console.log("avviato conversionamento");
    if (bindec === 1) {
      return indec(numerodaconvertire);
    }
    if (bindec === 0) {
      return inbin(numerodaconvertire);
    }
  };

  processForm = function(e) {
    var bindec, decbin, numeroconvertito;
    console.log("Avviato processForm");
    if (e.preventDefault) {
      e.preventDefault();
    }
    decbin = document.getElementById("decbin").checked;
    bindec = document.getElementById("bindec").checked;
    if (bindec !== false) {
      numeroconvertito = conversionamento(parseInt(document.getElementById("numero").value), 1);
    }
    if (decbin !== false) {
      numeroconvertito = conversionamento(parseInt(document.getElementById("numero").value), 0);
    }
    if (numeroconvertito === "Non va bene") {
      alert("Non hai messo un numero binario");
      return false;
    }
    alert("Il tuo numero convertito è" + numeroconvertito);
    console.log("Fermato processForm");
    return false;
    console.log("Fermato processForm");
    alert("Inizio!");
    return console.log("Fermato processForm");
  };

  console.log("Javascript iniziato");

  form = document.getElementById('conversione');

  if (form.attachEvent) {
    form.attachEvent("submit", processForm);
  } else {
    form.addEventListener("submit", processForm);
  }

}).call(this);
